name: "Python Comprehensive Linting"
description: "[DEV] Options for black, pycodestyle, flake8, pylint, isort and mypy"
inputs:
  root-dir-list:
    description: "List of directories to test"
    required: false
    default: "."
  packages:
    description: "List of packages to be used for formatting and linting"
    required: false
    default: black flake8
  max-line-length:
    description: "Maximum line length of packages to use"
    required: false
    default: "88"

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.root-dir-list }}
    - ${{ inputs.packages}}
    - ${{ inputs.max-line-length }}

branding:
  color: "blue"
  icon: "check-circle"