name: "Python Comprehensive Linting"
description: "[DEV] Options for black, pycodestyle, flake8, pylint, isort and mypy"
inputs:
  root-dir-list:
    description: "List of directories to test"
    required: false
    default: "."
  packages:
    description: "List of packages to be used for formatting and linting"
    required: false
    default: |
      black
      pycodestyle
      flake8
      pylint
      isort
      mypy

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.python-root-dir-list }}

branding:
  color: "blue"
  icon: "check-circle"