name: "Python Comprehensive Linting"
description: "[DEV] Options for black, pycodestyle, flake8, pylint, isort and mypy"
inputs:
  python-root-dir-list:
    description: "List of directories to test"
    required: false
    default: "."

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.python-root-dir-list }}