name: "Python Comprehensive Linting"
description: "[DEV] Options for black, pycodestyle, flake8, pylint, isort and mypy"
inputs:
  root-dir-list:
    description: "List of directories to test"
    required: false
    default: "."
  packages:
    description: "List of packages to be used for formatting and linting"
    required: false
    default: all

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.root-dir-list }}
    - ${{ inputs.packages}}

branding:
  color: "blue"
  icon: "check-circle"